export const OSMOSIS_CHAIN_REST = 'https://lcd-osmosis.blockapsis.com';

export const OSMOSIS_CURRENCIES = [
  {
    coinDenom: 'OSMO',
    coinMinimalDenom: 'uosmo',
    coinDecimals: 6,
    coinGeckoId: 'osmosis',
    coinImageUrl: '/tokens/osmo.svg',
    isStakeCurrency: true,
    isFeeCurrency: true,
  },
  {
    coinDenom: 'ION',
    coinMinimalDenom: 'uion',
    coinDecimals: 6,
    coinGeckoId: 'ion',
    coinImageUrl: '/tokens/ion.png',
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'regen',
    coinImageUrl: '/tokens/regen.png',
    coinMinimalDenom:
      'ibc/1DCC8A6CB5689018431323953344A9F6CC4D0BFB261E88C9F7777372C10CD076',
    coinDenom: 'REGEN',
    paths: [{ portId: 'transfer', channelId: 'channel-8' }],
    originChainId: 'regen-1',
    originCurrency: {
      coinDenom: 'REGEN',
      coinMinimalDenom: 'uregen',
      coinDecimals: 6,
      coinImageUrl: '/tokens/regen.png',
      coinGeckoId: 'regen',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 18,
    coinGeckoId: 'echelon',
    coinImageUrl: '/tokens/ech.png',
    coinMinimalDenom:
      'ibc/49C2B2C444B7C5F0066657A4DBF19D676E0D185FF721CFD3E14FA253BCB9BC04',
    coinDenom: 'ECH (channel-262)',
    paths: [{ portId: 'transfer', channelId: 'channel-262' }],
    originChainId: 'echelon_3000-3',
    originCurrency: {
      coinDenom: 'ECH',
      coinMinimalDenom: 'aechelon',
      coinDecimals: 18,
      coinGeckoId: 'echelon',
      coinImageUrl: '/tokens/ech.png',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 18,
    coinGeckoId: 'evmos',
    coinImageUrl: '/tokens/evmos.svg',
    coinMinimalDenom:
      'ibc/6AE98883D4D5D5FF9E50D7130F1305DA2FFA0C652D1DD9C123657C6B4EB2DF8A',
    coinDenom: 'EVMOS',
    paths: [{ portId: 'transfer', channelId: 'channel-204' }],
    originChainId: 'evmos_9001-2',
    originCurrency: {
      coinDenom: 'EVMOS',
      coinMinimalDenom: 'aevmos',
      coinDecimals: 18,
      coinGeckoId: 'evmos',
      coinImageUrl: '/tokens/evmos.svg',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'pool:jkl',
    coinImageUrl: '/tokens/jkl.svg',
    coinMinimalDenom:
      'ibc/8E697BDABE97ACE8773C6DF7402B2D1D5104DD1EEABE12608E3469B7F64C15BA',
    coinDenom: 'JKL (channel-412)',
    paths: [{ portId: 'transfer', channelId: 'channel-412' }],
    originChainId: 'jackal-1',
    originCurrency: {
      coinDenom: 'JKL',
      coinMinimalDenom: 'ujkl',
      coinDecimals: 6,
      coinGeckoId: 'pool:jkl',
      coinImageUrl: '/tokens/jkl.svg',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'pool:asvt',
    coinImageUrl: '/tokens/asvt.png',
    coinMinimalDenom:
      'ibc/AA1C80225BCA7B32ED1FC6ABF8B8E899BEB48ECDB4B417FD69873C6D715F97E7',
    coinDenom: 'ASVT (channel-169)',
    paths: [{ portId: 'transfer', channelId: 'channel-169' }],
    originChainId: 'juno-1',
    originCurrency: {
      type: 'cw20',
      contractAddress:
        'juno17wzaxtfdw5em7lc94yed4ylgjme63eh73lm3lutp2rhcxttyvpwsypjm4w',
      coinDenom: 'ASVT',
      coinMinimalDenom:
        'cw20:juno17wzaxtfdw5em7lc94yed4ylgjme63eh73lm3lutp2rhcxttyvpwsypjm4w:ASVT',
      coinDecimals: 6,
      coinGeckoId: 'pool:asvt',
      coinImageUrl: '/tokens/asvt.png',
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'usd-coin',
    coinImageUrl: '/tokens/usdc.svg',
    coinMinimalDenom:
      'ibc/D189335C6E4A68B513C10AB227BF1C1D38C746766278BA3EEB4FB14124F1D858',
    coinDenom: 'USDC',
    paths: [{ portId: 'transfer', channelId: 'channel-208' }],
    originChainId: 'axelar-dojo-1',
    originCurrency: {
      coinDenom: 'USDC',
      coinMinimalDenom: 'uusdc',
      coinDecimals: 6,
      coinGeckoId: 'usd-coin',
      coinImageUrl: '/tokens/usdc.svg',
      pegMechanism: 'collateralized',
    },
  },
  {
    coinDecimals: 18,
    coinGeckoId: 'weth',
    coinImageUrl: '/tokens/weth.png',
    coinMinimalDenom:
      'ibc/EA1D43981D5C9A1C4AAEA9C23BB1D4FA126BA9BC7020A25E0AE4AA841EA25DC5',
    coinDenom: 'WETH',
    paths: [{ portId: 'transfer', channelId: 'channel-208' }],
    originChainId: 'axelar-dojo-1',
    originCurrency: {
      coinDenom: 'WETH',
      coinMinimalDenom: 'weth-wei',
      coinDecimals: 18,
      coinGeckoId: 'weth',
      coinImageUrl: '/tokens/weth.png',
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'cosmos',
    coinImageUrl: '/tokens/atom.svg',
    coinMinimalDenom:
      'ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2',
    coinDenom: 'ATOM',
    paths: [{ portId: 'transfer', channelId: 'channel-0' }],
    originChainId: 'cosmoshub-4',
    originCurrency: {
      coinDenom: 'ATOM',
      coinMinimalDenom: 'uatom',
      coinDecimals: 6,
      coinGeckoId: 'cosmos',
      coinImageUrl: '/tokens/atom.svg',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'akash-network',
    coinImageUrl: '/tokens/akt.svg',
    coinMinimalDenom:
      'ibc/1480B8FD20AD5FCAE81EA87584D269547DD4D436843C1D20F15E00EB64743EF4',
    coinDenom: 'AKT',
    paths: [{ portId: 'transfer', channelId: 'channel-1' }],
    originChainId: 'akashnet-2',
    originCurrency: {
      coinDenom: 'AKT',
      coinMinimalDenom: 'uakt',
      coinDecimals: 6,
      coinGeckoId: 'akash-network',
      coinImageUrl: '/tokens/akt.svg',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'sentinel',
    coinImageUrl: '/tokens/dvpn.png',
    coinMinimalDenom:
      'ibc/9712DBB13B9631EDFA9BF61B55F1B2D290B2ADB67E3A4EB3A875F3B6081B3B84',
    coinDenom: 'DVPN',
    paths: [{ portId: 'transfer', channelId: 'channel-2' }],
    originChainId: 'sentinelhub-2',
    originCurrency: {
      coinDenom: 'DVPN',
      coinMinimalDenom: 'udvpn',
      coinDecimals: 6,
      coinGeckoId: 'sentinel',
      coinImageUrl: '/tokens/dvpn.png',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'iris-network',
    coinImageUrl: '/tokens/iris.svg',
    coinMinimalDenom:
      'ibc/7C4D60AA95E5A7558B0A364860979CA34B7FF8AAF255B87AF9E879374470CEC0',
    coinDenom: 'IRIS',
    paths: [{ portId: 'transfer', channelId: 'channel-6' }],
    originChainId: 'irishub-1',
    originCurrency: {
      coinDenom: 'IRIS',
      coinMinimalDenom: 'uiris',
      coinDecimals: 6,
      coinGeckoId: 'iris-network',
      coinImageUrl: '/tokens/iris.svg',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 8,
    coinGeckoId: 'crypto-com-chain',
    coinImageUrl: '/tokens/cro.png',
    coinMinimalDenom:
      'ibc/E6931F78057F7CC5DA0FD6CEF82FF39373A6E0452BF1FD76910B93292CF356C1',
    coinDenom: 'CRO',
    paths: [{ portId: 'transfer', channelId: 'channel-5' }],
    originChainId: 'crypto-org-chain-mainnet-1',
    originCurrency: {
      coinDenom: 'CRO',
      coinMinimalDenom: 'basecro',
      coinDecimals: 8,
      coinGeckoId: 'crypto-com-chain',
      coinImageUrl: '/tokens/cro.png',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'persistence',
    coinImageUrl: '/tokens/xprt.png',
    coinMinimalDenom:
      'ibc/A0CC0CF735BFB30E730C70019D4218A1244FF383503FF7579C9201AB93CA9293',
    coinDenom: 'XPRT',
    paths: [{ portId: 'transfer', channelId: 'channel-4' }],
    originChainId: 'core-1',
    originCurrency: {
      coinDenom: 'XPRT',
      coinMinimalDenom: 'uxprt',
      coinDecimals: 6,
      coinGeckoId: 'persistence',
      coinImageUrl: '/tokens/xprt.png',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'starname',
    coinImageUrl: '/tokens/iov.png',
    coinMinimalDenom:
      'ibc/52B1AA623B34EB78FD767CEA69E8D7FA6C9CFE1FBF49C5406268FD325E2CC2AC',
    coinDenom: 'IOV',
    paths: [{ portId: 'transfer', channelId: 'channel-15' }],
    originChainId: 'iov-mainnet-ibc',
    originCurrency: {
      coinDenom: 'IOV',
      coinMinimalDenom: 'uiov',
      coinDecimals: 6,
      coinGeckoId: 'starname',
      coinImageUrl: '/tokens/iov.png',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'pool:utick',
    coinImageUrl: '/tokens/tick.svg',
    coinMinimalDenom:
      'ibc/CD942F878C80FBE9DEAB8F8E57F592C7252D06335F193635AF002ACBD69139CC',
    coinDenom: 'TICK (channel-28)',
    paths: [{ portId: 'transfer', channelId: 'channel-28' }],
    originChainId: 'microtick-1',
    originCurrency: {
      coinDenom: 'TICK',
      coinMinimalDenom: 'utick',
      coinDecimals: 6,
      coinGeckoId: 'pool:utick',
      coinImageUrl: '/tokens/tick.svg',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'e-money',
    coinImageUrl: '/tokens/ngm.png',
    coinMinimalDenom:
      'ibc/1DC495FCEFDA068A3820F903EDBD78B942FBD204D7E93D3BA2B432E9669D1A59',
    coinDenom: 'NGM',
    paths: [{ portId: 'transfer', channelId: 'channel-37' }],
    originChainId: 'emoney-3',
    originCurrency: {
      coinDenom: 'NGM',
      coinMinimalDenom: 'ungm',
      coinDecimals: 6,
      coinGeckoId: 'e-money',
      coinImageUrl: '/tokens/ngm.png',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'e-money-eur',
    coinImageUrl: '/tokens/eeur.png',
    coinMinimalDenom:
      'ibc/5973C068568365FFF40DEDCF1A1CB7582B6116B731CD31A12231AE25E20B871F',
    coinDenom: 'EEUR',
    paths: [{ portId: 'transfer', channelId: 'channel-37' }],
    originChainId: 'emoney-3',
    originCurrency: {
      coinDenom: 'EEUR',
      coinMinimalDenom: 'eeur',
      coinDecimals: 6,
      coinGeckoId: 'e-money-eur',
      coinImageUrl: '/tokens/eeur.png',
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'juno-network',
    coinImageUrl: '/tokens/juno.svg',
    coinMinimalDenom:
      'ibc/46B44899322F3CD854D2D46DEEF881958467CDD4B3B10086DA49296BBED94BED',
    coinDenom: 'JUNO',
    paths: [{ portId: 'transfer', channelId: 'channel-42' }],
    originChainId: 'juno-1',
    originCurrency: {
      coinDenom: 'JUNO',
      coinMinimalDenom: 'ujuno',
      coinDecimals: 6,
      coinGeckoId: 'juno-network',
      coinImageUrl: '/tokens/juno.svg',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'pool:utick',
    coinImageUrl: '/tokens/tick.svg',
    coinMinimalDenom:
      'ibc/655BCEF3CDEBE32863FF281DBBE3B06160339E9897DC9C9C9821932A5F8BA6F8',
    coinDenom: 'TICK (channel-39)',
    paths: [{ portId: 'transfer', channelId: 'channel-39' }],
    originChainId: 'microtick-1',
    originCurrency: {
      coinDenom: 'TICK',
      coinMinimalDenom: 'utick',
      coinDecimals: 6,
      coinGeckoId: 'pool:utick',
      coinImageUrl: '/tokens/tick.svg',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 9,
    coinGeckoId: 'likecoin',
    coinImageUrl: '/tokens/like.svg',
    coinMinimalDenom:
      'ibc/9989AD6CCA39D1131523DB0617B50F6442081162294B4795E26746292467B525',
    coinDenom: 'LIKE',
    paths: [{ portId: 'transfer', channelId: 'channel-53' }],
    originChainId: 'likecoin-mainnet-2',
    originCurrency: {
      coinDenom: 'LIKE',
      coinMinimalDenom: 'nanolike',
      coinDecimals: 9,
      coinGeckoId: 'likecoin',
      coinImageUrl: '/tokens/like.svg',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'pool:uixo',
    coinImageUrl: '/tokens/ixo.png',
    coinMinimalDenom:
      'ibc/F3FF7A84A73B62921538642F9797C423D2B4C4ACB3C7FCFFCE7F12AA69909C4B',
    coinDenom: 'IXO',
    paths: [{ portId: 'transfer', channelId: 'channel-38' }],
    originChainId: 'impacthub-3',
    originCurrency: {
      coinDenom: 'IXO',
      coinMinimalDenom: 'uixo',
      coinDecimals: 6,
      coinGeckoId: 'pool:uixo',
      coinImageUrl: '/tokens/ixo.png',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'pool:uustc',
    coinImageUrl: '/tokens/ustc.png',
    coinMinimalDenom:
      'ibc/BE1BB42D4BE3C30D50B68D7C41DB4DFCE9678E8EF8C539F6E6A9345048894FCC',
    coinDenom: 'USTC (channel-72)',
    paths: [{ portId: 'transfer', channelId: 'channel-72' }],
    originChainId: 'columbus-5',
    originCurrency: {
      coinDenom: 'USTC',
      coinMinimalDenom: 'uusd',
      coinDecimals: 6,
      coinGeckoId: 'pool:uustc',
      coinImageUrl: '/tokens/ustc.png',
      isFeeCurrency: true,
      pegMechanism: 'algorithmic',
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'pool:ulunc',
    coinImageUrl: '/tokens/lunc.png',
    coinMinimalDenom:
      'ibc/0EF15DF2F02480ADE0BB6E85D9EBB5DAEA2836D3860E9F97F9AADE4F57A31AA0',
    coinDenom: 'LUNC (channel-72)',
    paths: [{ portId: 'transfer', channelId: 'channel-72' }],
    originChainId: 'columbus-5',
    originCurrency: {
      coinDenom: 'LUNC',
      coinMinimalDenom: 'uluna',
      coinDecimals: 6,
      coinGeckoId: 'pool:ulunc',
      coinImageUrl: '/tokens/lunc.png',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'bitcanna',
    coinImageUrl: '/tokens/bcna.svg',
    coinMinimalDenom:
      'ibc/D805F1DA50D31B96E4282C1D4181EDDFB1A44A598BFF5666F4B43E4B8BEA95A5',
    coinDenom: 'BCNA',
    paths: [{ portId: 'transfer', channelId: 'channel-51' }],
    originChainId: 'bitcanna-1',
    originCurrency: {
      coinDenom: 'BCNA',
      coinMinimalDenom: 'ubcna',
      coinDecimals: 6,
      coinGeckoId: 'bitcanna',
      coinImageUrl: '/tokens/bcna.svg',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'pool:ubtsg',
    coinImageUrl: '/tokens/btsg.svg',
    coinMinimalDenom:
      'ibc/4E5444C35610CC76FC94E7F7886B93121175C28262DDFDDE6F84E82BF2425452',
    coinDenom: 'BTSG',
    paths: [{ portId: 'transfer', channelId: 'channel-73' }],
    originChainId: 'bitsong-2b',
    originCurrency: {
      coinDenom: 'BTSG',
      coinMinimalDenom: 'ubtsg',
      coinDecimals: 6,
      coinGeckoId: 'pool:ubtsg',
      coinImageUrl: '/tokens/btsg.svg',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'pool:uxki',
    coinImageUrl: '/tokens/xki.svg',
    coinMinimalDenom:
      'ibc/B547DC9B897E7C3AA5B824696110B8E3D2C31E3ED3F02FF363DCBAD82457E07E',
    coinDenom: 'XKI',
    paths: [{ portId: 'transfer', channelId: 'channel-77' }],
    originChainId: 'kichain-2',
    originCurrency: {
      coinDenom: 'XKI',
      coinMinimalDenom: 'uxki',
      coinDecimals: 6,
      coinGeckoId: 'pool:uxki',
      coinImageUrl: '/tokens/xki.svg',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'terra-krw',
    coinImageUrl: '/tokens/krtc.png',
    coinMinimalDenom:
      'ibc/204A582244FC241613DBB50B04D1D454116C58C4AF7866C186AA0D6EEAD42780',
    coinDenom: 'KRTC (channel-72)',
    paths: [{ portId: 'transfer', channelId: 'channel-72' }],
    originChainId: 'columbus-5',
    originCurrency: {
      coinDenom: 'KRTC',
      coinMinimalDenom: 'ukrw',
      coinDecimals: 6,
      coinGeckoId: 'terra-krw',
      coinImageUrl: '/tokens/krtc.png',
      pegMechanism: 'algorithmic',
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'secret',
    coinImageUrl: '/tokens/scrt.svg',
    coinMinimalDenom:
      'ibc/0954E1C28EB7AF5B72D24F3BC2B47BBB2FDF91BDDFD57B74B99E133AED40972A',
    coinDenom: 'SCRT',
    paths: [{ portId: 'transfer', channelId: 'channel-88' }],
    originChainId: 'secret-4',
    originCurrency: {
      coinDenom: 'SCRT',
      coinMinimalDenom: 'uscrt',
      coinDecimals: 6,
      coinGeckoId: 'secret',
      coinImageUrl: '/tokens/scrt.svg',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'medibloc',
    coinImageUrl: '/tokens/med.png',
    coinMinimalDenom:
      'ibc/3BCCC93AD5DF58D11A6F8A05FA8BC801CBA0BA61A981F57E91B8B598BF8061CB',
    coinDenom: 'MED',
    paths: [{ portId: 'transfer', channelId: 'channel-82' }],
    originChainId: 'panacea-3',
    originCurrency: {
      coinDenom: 'MED',
      coinMinimalDenom: 'umed',
      coinDecimals: 6,
      coinGeckoId: 'medibloc',
      coinImageUrl: '/tokens/med.png',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 0,
    coinGeckoId: 'bostrom',
    coinImageUrl: '/tokens/boot.png',
    coinMinimalDenom:
      'ibc/FE2CD1E6828EC0FAB8AF39BAC45BC25B965BA67CCBC50C13A14BD610B0D1E2C4',
    coinDenom: 'BOOT',
    paths: [{ portId: 'transfer', channelId: 'channel-95' }],
    originChainId: 'bostrom',
    originCurrency: {
      coinDenom: 'BOOT',
      coinMinimalDenom: 'boot',
      coinDecimals: 0,
      coinGeckoId: 'bostrom',
      coinImageUrl: '/tokens/boot.png',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'comdex',
    coinImageUrl: '/tokens/cmdx.png',
    coinMinimalDenom:
      'ibc/EA3E1640F9B1532AB129A571203A0B9F789A7F14BB66E350DCBFA18E1A1931F0',
    coinDenom: 'CMDX',
    paths: [{ portId: 'transfer', channelId: 'channel-87' }],
    originChainId: 'comdex-1',
    originCurrency: {
      coinDenom: 'CMDX',
      coinMinimalDenom: 'ucmdx',
      coinDecimals: 6,
      coinGeckoId: 'comdex',
      coinImageUrl: '/tokens/cmdx.png',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 9,
    coinGeckoId: 'cheqd-network',
    coinImageUrl: '/tokens/cheq.svg',
    coinMinimalDenom:
      'ibc/7A08C6F11EF0F59EB841B9F788A87EC9F2361C7D9703157EC13D940DC53031FA',
    coinDenom: 'CHEQ',
    paths: [{ portId: 'transfer', channelId: 'channel-108' }],
    originChainId: 'cheqd-mainnet-1',
    originCurrency: {
      coinDenom: 'CHEQ',
      coinMinimalDenom: 'ncheq',
      coinDecimals: 9,
      coinGeckoId: 'cheqd-network',
      coinImageUrl: '/tokens/cheq.svg',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'pool:ustars',
    coinImageUrl: '/tokens/stars.png',
    coinMinimalDenom:
      'ibc/987C17B11ABC2B20019178ACE62929FE9840202CE79498E29FE8E5CB02B7C0A4',
    coinDenom: 'STARS',
    paths: [{ portId: 'transfer', channelId: 'channel-75' }],
    originChainId: 'stargaze-1',
    originCurrency: {
      coinDenom: 'STARS',
      coinMinimalDenom: 'ustars',
      coinDecimals: 6,
      coinGeckoId: 'pool:ustars',
      coinImageUrl: '/tokens/stars.png',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'pool:uhuahua',
    coinImageUrl: '/tokens/huahua.png',
    coinMinimalDenom:
      'ibc/B9E0A1A524E98BB407D3CED8720EFEFD186002F90C1B1B7964811DD0CCC12228',
    coinDenom: 'HUAHUA',
    paths: [{ portId: 'transfer', channelId: 'channel-113' }],
    originChainId: 'chihuahua-1',
    originCurrency: {
      coinDenom: 'HUAHUA',
      coinMinimalDenom: 'uhuahua',
      coinDecimals: 6,
      coinGeckoId: 'pool:uhuahua',
      coinImageUrl: '/tokens/huahua.png',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'pool:ulum',
    coinImageUrl: '/tokens/lum.svg',
    coinMinimalDenom:
      'ibc/8A34AF0C1943FD0DFCDE9ADBF0B2C9959C45E87E6088EA2FC6ADACD59261B8A2',
    coinDenom: 'LUM',
    paths: [{ portId: 'transfer', channelId: 'channel-115' }],
    originChainId: 'lum-network-1',
    originCurrency: {
      coinDenom: 'LUM',
      coinMinimalDenom: 'ulum',
      coinDecimals: 6,
      coinGeckoId: 'pool:ulum',
      coinImageUrl: '/tokens/lum.svg',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'vidulum',
    coinImageUrl: '/tokens/vdl.svg',
    coinMinimalDenom:
      'ibc/E7B35499CFBEB0FF5778127ABA4FB2C4B79A6B8D3D831D4379C4048C238796BD',
    coinDenom: 'VDL',
    paths: [{ portId: 'transfer', channelId: 'channel-124' }],
    originChainId: 'vidulum-1',
    originCurrency: {
      coinDenom: 'VDL',
      coinMinimalDenom: 'uvdl',
      coinDecimals: 6,
      coinGeckoId: 'vidulum',
      coinImageUrl: '/tokens/vdl.svg',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'pool:udsm',
    coinImageUrl: '/tokens/dsm.svg',
    coinMinimalDenom:
      'ibc/EA4C0A9F72E2CEDF10D0E7A9A6A22954DB3444910DB5BE980DF59B05A46DAD1C',
    coinDenom: 'DSM',
    paths: [{ portId: 'transfer', channelId: 'channel-135' }],
    originChainId: 'desmos-mainnet',
    originCurrency: {
      coinDenom: 'DSM',
      coinMinimalDenom: 'udsm',
      coinDecimals: 6,
      coinGeckoId: 'pool:udsm',
      coinImageUrl: '/tokens/dsm.svg',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'pool:udig',
    coinImageUrl: '/tokens/dig.png',
    coinMinimalDenom:
      'ibc/307E5C96C8F60D1CBEE269A9A86C0834E1DB06F2B3788AE4F716EDB97A48B97D',
    coinDenom: 'DIG',
    paths: [{ portId: 'transfer', channelId: 'channel-128' }],
    originChainId: 'dig-1',
    originCurrency: {
      coinDenom: 'DIG',
      coinMinimalDenom: 'udig',
      coinDecimals: 6,
      coinGeckoId: 'pool:udig',
      coinImageUrl: '/tokens/dig.png',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'pool:ugraviton',
    coinImageUrl: '/tokens/grav.svg',
    coinMinimalDenom:
      'ibc/E97634A40119F1898989C2A23224ED83FDD0A57EA46B3A094E287288D1672B44',
    coinDenom: 'GRAV',
    paths: [{ portId: 'transfer', channelId: 'channel-144' }],
    originChainId: 'gravity-bridge-3',
    originCurrency: {
      coinDenom: 'GRAV',
      coinMinimalDenom: 'ugraviton',
      coinDecimals: 6,
      coinGeckoId: 'pool:ugraviton',
      coinImageUrl: '/tokens/grav.svg',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'band-protocol',
    coinImageUrl: '/tokens/band.svg',
    coinMinimalDenom:
      'ibc/F867AE2112EFE646EC71A25CD2DFABB8927126AC1E19F1BBF0FF693A4ECA05DE',
    coinDenom: 'BAND',
    paths: [{ portId: 'transfer', channelId: 'channel-148' }],
    originChainId: 'laozi-mainnet',
    originCurrency: {
      coinDenom: 'BAND',
      coinMinimalDenom: 'uband',
      coinDecimals: 6,
      coinGeckoId: 'band-protocol',
      coinImageUrl: '/tokens/band.svg',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'pool:usomm',
    coinImageUrl: '/tokens/somm.png',
    coinMinimalDenom:
      'ibc/9BBA9A1C257E971E38C1422780CE6F0B0686F0A3085E2D61118D904BFE0F5F5E',
    coinDenom: 'SOMM',
    paths: [{ portId: 'transfer', channelId: 'channel-165' }],
    originChainId: 'sommelier-3',
    originCurrency: {
      coinDenom: 'SOMM',
      coinMinimalDenom: 'usomm',
      coinDecimals: 6,
      coinGeckoId: 'pool:usomm',
      coinImageUrl: '/tokens/somm.png',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 18,
    coinGeckoId: 'pool:rowan',
    coinImageUrl: '/tokens/rowan.svg',
    coinMinimalDenom:
      'ibc/8318FD63C42203D16DDCAF49FE10E8590669B3219A3E87676AC9DA50722687FB',
    coinDenom: 'ROWAN',
    paths: [{ portId: 'transfer', channelId: 'channel-47' }],
    originChainId: 'sifchain-1',
    originCurrency: {
      coinDenom: 'ROWAN',
      coinMinimalDenom: 'rowan',
      coinDecimals: 18,
      coinGeckoId: 'pool:rowan',
      coinImageUrl: '/tokens/rowan.svg',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'neta',
    coinImageUrl: '/tokens/neta.svg',
    coinMinimalDenom:
      'ibc/297C64CC42B5A8D8F82FE2EBE208A6FE8F94B86037FA28C4529A23701C228F7A',
    coinDenom: 'NETA',
    paths: [{ portId: 'transfer', channelId: 'channel-169' }],
    originChainId: 'juno-1',
    originCurrency: {
      type: 'cw20',
      contractAddress:
        'juno168ctmpyppk90d34p3jjy658zf5a5l3w8wk35wht6ccqj4mr0yv8s4j5awr',
      coinDenom: 'NETA',
      coinMinimalDenom:
        'cw20:juno168ctmpyppk90d34p3jjy658zf5a5l3w8wk35wht6ccqj4mr0yv8s4j5awr:NETA',
      coinDecimals: 6,
      coinGeckoId: 'neta',
      coinImageUrl: '/tokens/neta.svg',
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'usd-coin',
    coinImageUrl: '/tokens/gusdc.png',
    coinMinimalDenom:
      'ibc/9F9B07EF9AD291167CF5700628145DE1DEB777C2CFC7907553B24446515F6D0E',
    coinDenom: 'USDC.grv (channel-144)',
    paths: [{ portId: 'transfer', channelId: 'channel-144' }],
    originChainId: 'gravity-bridge-3',
    originCurrency: {
      coinDenom: 'USDC.grv',
      coinMinimalDenom: 'gravity0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48',
      coinDecimals: 6,
      coinGeckoId: 'usd-coin',
      coinImageUrl: '/tokens/gusdc.png',
      pegMechanism: 'collateralized',
    },
  },
  {
    coinDecimals: 18,
    coinGeckoId: 'ethereum',
    coinImageUrl: '/tokens/gweth.png',
    coinMinimalDenom:
      'ibc/65381C5F3FD21442283D56925E62EA524DED8B6927F0FF94E21E0020954C40B5',
    coinDenom: 'WETH.grv (channel-144)',
    paths: [{ portId: 'transfer', channelId: 'channel-144' }],
    originChainId: 'gravity-bridge-3',
    originCurrency: {
      coinDenom: 'WETH.grv',
      coinMinimalDenom: 'gravity0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2',
      coinDecimals: 18,
      coinGeckoId: 'ethereum',
      coinImageUrl: '/tokens/gweth.png',
    },
  },
  {
    coinDecimals: 18,
    coinGeckoId: 'dai',
    coinImageUrl: '/tokens/gdai.png',
    coinMinimalDenom:
      'ibc/F292A17CF920E3462C816CBE6B042E779F676CAB59096904C4C1C966413E3DF5',
    coinDenom: 'DAI.grv (channel-144)',
    paths: [{ portId: 'transfer', channelId: 'channel-144' }],
    originChainId: 'gravity-bridge-3',
    originCurrency: {
      coinDenom: 'DAI.grv',
      coinMinimalDenom: 'gravity0x6B175474E89094C44Da98b954EedeAC495271d0F',
      coinDecimals: 18,
      coinGeckoId: 'dai',
      coinImageUrl: '/tokens/gdai.png',
      pegMechanism: 'collateralized',
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'pool:udarc',
    coinImageUrl: '/tokens/darc.svg',
    coinMinimalDenom:
      'ibc/346786EA82F41FE55FAD14BF69AD8BA9B36985406E43F3CB23E6C45A285A9593',
    coinDenom: 'DARC',
    paths: [{ portId: 'transfer', channelId: 'channel-171' }],
    originChainId: 'darchub',
    originCurrency: {
      coinDenom: 'DARC',
      coinMinimalDenom: 'udarc',
      coinDecimals: 6,
      coinGeckoId: 'pool:udarc',
      coinImageUrl: '/tokens/darc.svg',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'pool:uumee',
    coinImageUrl: '/tokens/umee.png',
    coinMinimalDenom:
      'ibc/67795E528DF67C5606FC20F824EA39A6EF55BA133F4DC79C90A8C47A0901E17C',
    coinDenom: 'UMEE',
    paths: [{ portId: 'transfer', channelId: 'channel-184' }],
    originChainId: 'umee-1',
    originCurrency: {
      coinDenom: 'UMEE',
      coinMinimalDenom: 'uumee',
      coinDecimals: 6,
      coinGeckoId: 'pool:uumee',
      coinImageUrl: '/tokens/umee.png',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'decentr',
    coinImageUrl: '/tokens/dec.svg',
    coinMinimalDenom:
      'ibc/9BCB27203424535B6230D594553F1659C77EC173E36D9CF4759E7186EE747E84',
    coinDenom: 'DEC',
    paths: [{ portId: 'transfer', channelId: 'channel-181' }],
    originChainId: 'mainnet-3',
    originCurrency: {
      coinDenom: 'DEC',
      coinMinimalDenom: 'udec',
      coinDecimals: 6,
      coinGeckoId: 'decentr',
      coinImageUrl: '/tokens/dec.svg',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 18,
    coinGeckoId: 'pstake-finance',
    coinImageUrl: '/tokens/pstake.png',
    coinMinimalDenom:
      'ibc/8061A06D3BD4D52C4A28FFECF7150D370393AF0BA661C3776C54FF32836C3961',
    coinDenom: 'PSTAKE (channel-4)',
    paths: [
      { portId: 'transfer', channelId: 'channel-4' },
      { portId: 'transfer', channelId: 'channel-38' },
    ],
    originChainId: 'gravity-bridge-3',
    originCurrency: {
      coinDenom: 'PSTAKE',
      coinMinimalDenom: 'gravity0xfB5c6815cA3AC72Ce9F5006869AE67f18bF77006',
      coinDecimals: 18,
      coinGeckoId: 'pstake-finance',
      coinImageUrl: '/tokens/pstake.png',
    },
  },
  {
    coinDecimals: 3,
    coinGeckoId: 'pool:marble',
    coinImageUrl: '/tokens/marble.svg',
    coinMinimalDenom:
      'ibc/F6B691D5F7126579DDC87357B09D653B47FDCE0A3383FF33C8D8B544FE29A8A6',
    coinDenom: 'MARBLE',
    paths: [{ portId: 'transfer', channelId: 'channel-169' }],
    originChainId: 'juno-1',
    originCurrency: {
      type: 'cw20',
      contractAddress:
        'juno1g2g7ucurum66d42g8k5twk34yegdq8c82858gz0tq2fc75zy7khssgnhjl',
      coinDenom: 'MARBLE',
      coinMinimalDenom:
        'cw20:juno1g2g7ucurum66d42g8k5twk34yegdq8c82858gz0tq2fc75zy7khssgnhjl:MARBLE',
      coinDecimals: 3,
      coinGeckoId: 'pool:marble',
      coinImageUrl: '/tokens/marble.svg',
    },
  },
  {
    coinDecimals: 8,
    coinGeckoId: 'switcheo',
    coinImageUrl: '/tokens/swth.png',
    coinMinimalDenom:
      'ibc/8FEFAE6AECF6E2A255585617F781F35A8D5709A545A804482A261C0C9548A9D3',
    coinDenom: 'SWTH',
    paths: [{ portId: 'transfer', channelId: 'channel-188' }],
    originChainId: 'carbon-1',
    originCurrency: {
      coinDenom: 'SWTH',
      coinMinimalDenom: 'swth',
      coinDecimals: 8,
      coinGeckoId: 'switcheo',
      coinImageUrl: '/tokens/swth.png',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'cerberus-2',
    coinImageUrl: '/tokens/crbrus.png',
    coinMinimalDenom:
      'ibc/41999DF04D9441DAC0DF5D8291DF4333FBCBA810FFD63FDCE34FDF41EF37B6F7',
    coinDenom: 'CRBRUS',
    paths: [{ portId: 'transfer', channelId: 'channel-212' }],
    originChainId: 'cerberus-chain-1',
    originCurrency: {
      coinDenom: 'CRBRUS',
      coinMinimalDenom: 'ucrbrus',
      coinDecimals: 6,
      coinGeckoId: 'cerberus-2',
      coinImageUrl: '/tokens/crbrus.png',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'pool:hope',
    coinImageUrl: '/tokens/hope.svg',
    coinMinimalDenom:
      'ibc/C2A2E9CA95DDD4828B75124B5E27B8401C7D8493BC48353D418CBFC04565899B',
    coinDenom: 'HOPE (channel-169)',
    paths: [{ portId: 'transfer', channelId: 'channel-169' }],
    originChainId: 'juno-1',
    originCurrency: {
      type: 'cw20',
      contractAddress:
        'juno1re3x67ppxap48ygndmrc7har2cnc7tcxtm9nplcas4v0gc3wnmvs3s807z',
      coinDenom: 'HOPE',
      coinMinimalDenom:
        'cw20:juno1re3x67ppxap48ygndmrc7har2cnc7tcxtm9nplcas4v0gc3wnmvs3s807z:HOPE',
      coinDecimals: 6,
      coinGeckoId: 'pool:hope',
      coinImageUrl: '/tokens/hope.svg',
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'pool:rac',
    coinImageUrl: '/tokens/rac.svg',
    coinMinimalDenom:
      'ibc/6BDB4C8CCD45033F9604E4B93ED395008A753E01EECD6992E7D1EA23D9D3B788',
    coinDenom: 'RAC (channel-169)',
    paths: [{ portId: 'transfer', channelId: 'channel-169' }],
    originChainId: 'juno-1',
    originCurrency: {
      type: 'cw20',
      contractAddress:
        'juno1r4pzw8f9z0sypct5l9j906d47z998ulwvhvqe5xdwgy8wf84583sxwh0pa',
      coinDenom: 'RAC',
      coinMinimalDenom:
        'cw20:juno1r4pzw8f9z0sypct5l9j906d47z998ulwvhvqe5xdwgy8wf84583sxwh0pa:RAC',
      coinDecimals: 6,
      coinGeckoId: 'pool:rac',
      coinImageUrl: '/tokens/rac.svg',
    },
  },
  {
    coinDecimals: 18,
    coinGeckoId: 'dai',
    coinImageUrl: '/tokens/dai.svg',
    coinMinimalDenom:
      'ibc/0CD3A0285E1341859B5E86B6AB7682F023D03E97607CCC1DC95706411D866DF7',
    coinDenom: 'DAI',
    paths: [{ portId: 'transfer', channelId: 'channel-208' }],
    originChainId: 'axelar-dojo-1',
    originCurrency: {
      coinDenom: 'DAI',
      coinMinimalDenom: 'dai-wei',
      coinDecimals: 18,
      coinGeckoId: 'dai',
      coinImageUrl: '/tokens/dai.svg',
      pegMechanism: 'collateralized',
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'pool:block',
    coinImageUrl: '/tokens/block.svg',
    coinMinimalDenom:
      'ibc/DB9755CB6FE55192948AE074D18FA815E1429D3D374D5BDA8D89623C6CF235C3',
    coinDenom: 'BLOCK (channel-169)',
    paths: [{ portId: 'transfer', channelId: 'channel-169' }],
    originChainId: 'juno-1',
    originCurrency: {
      type: 'cw20',
      contractAddress:
        'juno1y9rf7ql6ffwkv02hsgd4yruz23pn4w97p75e2slsnkm0mnamhzysvqnxaq',
      coinDenom: 'BLOCK',
      coinMinimalDenom:
        'cw20:juno1y9rf7ql6ffwkv02hsgd4yruz23pn4w97p75e2slsnkm0mnamhzysvqnxaq:BLOCK',
      coinDecimals: 6,
      coinGeckoId: 'pool:block',
      coinImageUrl: '/tokens/block.svg',
    },
  },
  {
    coinDecimals: 18,
    coinGeckoId: 'frax',
    coinImageUrl: '/tokens/frax.svg',
    coinMinimalDenom:
      'ibc/0E43EDE2E2A3AFA36D0CD38BDDC0B49FECA64FA426A82E102F304E430ECF46EE',
    coinDenom: 'FRAX (channel-208)',
    paths: [{ portId: 'transfer', channelId: 'channel-208' }],
    originChainId: 'axelar-dojo-1',
    originCurrency: {
      coinDenom: 'FRAX',
      coinMinimalDenom: 'frax-wei',
      coinDecimals: 18,
      coinGeckoId: 'frax',
      coinImageUrl: '/tokens/frax.svg',
      pegMechanism: 'hybrid',
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'tether',
    coinImageUrl: '/tokens/usdt.svg',
    coinMinimalDenom:
      'ibc/8242AD24008032E457D2E12D46588FD39FB54FB29680C6C7663D296B383C37C4',
    coinDenom: 'USDT (channel-208)',
    paths: [{ portId: 'transfer', channelId: 'channel-208' }],
    originChainId: 'axelar-dojo-1',
    originCurrency: {
      coinDenom: 'USDT',
      coinMinimalDenom: 'uusdt',
      coinDecimals: 6,
      coinGeckoId: 'tether',
      coinImageUrl: '/tokens/usdt.svg',
      pegMechanism: 'collateralized',
    },
  },
  {
    coinDecimals: 18,
    coinGeckoId: 'fetch-ai',
    coinImageUrl: '/tokens/fet.png',
    coinMinimalDenom:
      'ibc/5D1F516200EE8C6B2354102143B78A2DEDA25EDE771AC0F8DC3C1837C8FD4447',
    coinDenom: 'FET',
    paths: [{ portId: 'transfer', channelId: 'channel-229' }],
    originChainId: 'fetchhub-4',
    originCurrency: {
      coinDenom: 'FET',
      coinMinimalDenom: 'afet',
      coinDecimals: 18,
      coinGeckoId: 'fetch-ai',
      coinImageUrl: '/tokens/fet.png',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'pool:umntl',
    coinImageUrl: '/tokens/mntl.png',
    coinMinimalDenom:
      'ibc/CBA34207E969623D95D057D9B11B0C8B32B89A71F170577D982FDDE623813FFC',
    coinDenom: 'MNTL',
    paths: [{ portId: 'transfer', channelId: 'channel-232' }],
    originChainId: 'mantle-1',
    originCurrency: {
      coinDenom: 'MNTL',
      coinMinimalDenom: 'umntl',
      coinDecimals: 6,
      coinGeckoId: 'pool:umntl',
      coinImageUrl: '/tokens/mntl.png',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 9,
    coinGeckoId: 'provenance-blockchain',
    coinImageUrl: '/tokens/hash.svg',
    coinMinimalDenom:
      'ibc/CE5BFF1D9BADA03BB5CCA5F56939392A761B53A10FBD03B37506669C3218D3B2',
    coinDenom: 'HASH (channel-222)',
    paths: [{ portId: 'transfer', channelId: 'channel-222' }],
    originChainId: 'pio-mainnet-1',
    originCurrency: {
      coinDenom: 'HASH',
      coinMinimalDenom: 'nhash',
      coinGeckoId: 'provenance-blockchain',
      coinDecimals: 9,
      coinImageUrl: '/tokens/hash.svg',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 8,
    coinGeckoId: 'wrapped-bitcoin',
    coinImageUrl: '/tokens/gwbtc.png',
    coinMinimalDenom:
      'ibc/C9B0D48FD2C5B91135F118FF2484551888966590D7BDC20F6A87308DBA670796',
    coinDenom: 'WBTC.grv (channel-144)',
    paths: [{ portId: 'transfer', channelId: 'channel-144' }],
    originChainId: 'gravity-bridge-3',
    originCurrency: {
      coinDenom: 'WBTC.grv',
      coinMinimalDenom: 'gravity0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599',
      coinDecimals: 8,
      coinGeckoId: 'wrapped-bitcoin',
      coinImageUrl: '/tokens/gwbtc.png',
    },
  },
  {
    coinDecimals: 0,
    coinGeckoId: 'pool:dhk',
    coinImageUrl: '/tokens/dhk.svg',
    coinMinimalDenom:
      'ibc/52E12CF5CA2BB903D84F5298B4BFD725D66CAB95E09AA4FC75B2904CA5485FEB',
    coinDenom: 'DHK (channel-169)',
    paths: [{ portId: 'transfer', channelId: 'channel-169' }],
    originChainId: 'juno-1',
    originCurrency: {
      type: 'cw20',
      contractAddress:
        'juno1tdjwrqmnztn2j3sj2ln9xnyps5hs48q3ddwjrz7jpv6mskappjys5czd49',
      coinDenom: 'DHK',
      coinMinimalDenom:
        'cw20:juno1tdjwrqmnztn2j3sj2ln9xnyps5hs48q3ddwjrz7jpv6mskappjys5czd49:DHK',
      coinDecimals: 0,
      coinGeckoId: 'pool:dhk',
      coinImageUrl: '/tokens/dhk.svg',
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'pool:uglx',
    coinImageUrl: '/tokens/glx.svg',
    coinMinimalDenom:
      'ibc/F49DE040EBA5AB2FAD5F660C2A1DDF98A68470FAE82229818BE775EBF3EE79F2',
    coinDenom: 'GLX (channel-236)',
    paths: [{ portId: 'transfer', channelId: 'channel-236' }],
    originChainId: 'galaxy-1',
    originCurrency: {
      coinDenom: 'GLX',
      coinMinimalDenom: 'uglx',
      coinDecimals: 6,
      coinGeckoId: 'pool:uglx',
      coinImageUrl: '/tokens/glx.svg',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'pool:raw',
    coinImageUrl: '/tokens/raw.png',
    coinMinimalDenom:
      'ibc/00B6E60AD3D65CBEF5579AC8AF609527C0B57535B6E32D96C80A735344FD9DCC',
    coinDenom: 'RAW (channel-169)',
    paths: [{ portId: 'transfer', channelId: 'channel-169' }],
    originChainId: 'juno-1',
    originCurrency: {
      type: 'cw20',
      contractAddress:
        'juno15u3dt79t6sxxa3x3kpkhzsy56edaa5a66wvt3kxmukqjz2sx0hes5sn38g',
      coinDenom: 'RAW',
      coinMinimalDenom:
        'cw20:juno15u3dt79t6sxxa3x3kpkhzsy56edaa5a66wvt3kxmukqjz2sx0hes5sn38g:RAW',
      coinDecimals: 6,
      coinGeckoId: 'pool:raw',
      coinImageUrl: '/tokens/raw.png',
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'pool:umeme',
    coinImageUrl: '/tokens/meme.png',
    coinMinimalDenom:
      'ibc/67C89B8B0A70C08F093C909A4DD996DD10E0494C87E28FD9A551697BF173D4CA',
    coinDenom: 'MEME (channel-238)',
    paths: [{ portId: 'transfer', channelId: 'channel-238' }],
    originChainId: 'meme-1',
    originCurrency: {
      coinDenom: 'MEME',
      coinMinimalDenom: 'umeme',
      coinDecimals: 6,
      coinGeckoId: 'pool:umeme',
      coinImageUrl: '/tokens/meme.png',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 8,
    coinGeckoId: 'wrapped-bitcoin',
    coinImageUrl: '/tokens/wbtc.png',
    coinMinimalDenom:
      'ibc/D1542AA8762DB13087D8364F3EA6509FD6F009A34F00426AF9E4F9FA85CBBF1F',
    coinDenom: 'WBTC',
    paths: [{ portId: 'transfer', channelId: 'channel-208' }],
    originChainId: 'axelar-dojo-1',
    originCurrency: {
      coinDenom: 'WBTC',
      coinMinimalDenom: 'wbtc-satoshi',
      coinDecimals: 8,
      coinGeckoId: 'wrapped-bitcoin',
      coinImageUrl: '/tokens/wbtc.png',
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'rizon',
    coinImageUrl: '/tokens/atolo.svg',
    coinMinimalDenom:
      'ibc/2716E3F2E146664BEFA9217F1A03BFCEDBCD5178B3C71CACB1A0D7584451D219',
    coinDenom: 'ATOLO (channel-221)',
    paths: [{ portId: 'transfer', channelId: 'channel-221' }],
    originChainId: 'titan-1',
    originCurrency: {
      coinDenom: 'ATOLO',
      coinMinimalDenom: 'uatolo',
      coinDecimals: 6,
      coinGeckoId: 'rizon',
      coinImageUrl: '/tokens/atolo.svg',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'pool:joe',
    coinImageUrl: '/tokens/joe.png',
    coinMinimalDenom:
      'ibc/0CB9DB3441D0D50F35699DEE22B9C965487E83FB2D9F483D1CC5CA34E856C484',
    coinDenom: 'JOE (channel-169)',
    paths: [{ portId: 'transfer', channelId: 'channel-169' }],
    originChainId: 'juno-1',
    originCurrency: {
      type: 'cw20',
      contractAddress:
        'juno1n7n7d5088qlzlj37e9mgmkhx6dfgtvt02hqxq66lcap4dxnzdhwqfmgng3',
      coinDenom: 'JOE',
      coinMinimalDenom:
        'cw20:juno1n7n7d5088qlzlj37e9mgmkhx6dfgtvt02hqxq66lcap4dxnzdhwqfmgng3:JOE',
      coinDecimals: 6,
      coinGeckoId: 'pool:joe',
      coinImageUrl: '/tokens/joe.png',
    },
  },
  {
    coinDecimals: 18,
    coinGeckoId: 'injective-protocol',
    coinImageUrl: '/tokens/inj.svg',
    coinMinimalDenom:
      'ibc/64BA6E31FE887D66C6F8F31C7B1A80C7CA179239677B4088BB55F5EA07DBE273',
    coinDenom: 'INJ',
    paths: [{ portId: 'transfer', channelId: 'channel-122' }],
    originChainId: 'injective-1',
    originCurrency: {
      coinDenom: 'INJ',
      coinMinimalDenom: 'inj',
      coinDecimals: 18,
      coinGeckoId: 'injective-protocol',
      coinImageUrl: '/tokens/inj.svg',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'terra-luna-2',
    coinImageUrl: '/tokens/luna.svg',
    coinMinimalDenom:
      'ibc/785AFEC6B3741100D15E7AF01374E3C4C36F24888E96479B1C33F5C71F364EF9',
    coinDenom: 'LUNA (channel-251)',
    paths: [{ portId: 'transfer', channelId: 'channel-251' }],
    originChainId: 'phoenix-1',
    originCurrency: {
      coinDenom: 'LUNA',
      coinMinimalDenom: 'uluna',
      coinDecimals: 6,
      coinGeckoId: 'terra-luna-2',
      coinImageUrl: '/tokens/luna.svg',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'kava',
    coinImageUrl: '/tokens/kava.png',
    coinMinimalDenom:
      'ibc/57AA1A70A4BC9769C525EBF6386F7A21536E04A79D62E1981EFCEF9428EBB205',
    coinDenom: 'KAVA',
    paths: [{ portId: 'transfer', channelId: 'channel-143' }],
    originChainId: 'kava_2222-10',
    originCurrency: {
      coinDenom: 'KAVA',
      coinMinimalDenom: 'ukava',
      coinDecimals: 6,
      coinGeckoId: 'kava',
      coinImageUrl: '/tokens/kava.png',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 18,
    coinGeckoId: 'chainlink',
    coinImageUrl: '/tokens/link.svg',
    coinMinimalDenom:
      'ibc/D3327A763C23F01EC43D1F0DB3CEFEC390C362569B6FD191F40A5192F8960049',
    coinDenom: 'LINK',
    paths: [{ portId: 'transfer', channelId: 'channel-208' }],
    originChainId: 'axelar-dojo-1',
    originCurrency: {
      coinDenom: 'LINK',
      coinMinimalDenom: 'link-wei',
      coinDecimals: 18,
      coinGeckoId: 'chainlink',
      coinImageUrl: '/tokens/link.svg',
    },
  },
  {
    coinDecimals: 18,
    coinGeckoId: 'maker',
    coinImageUrl: '/tokens/mkr.svg',
    coinMinimalDenom:
      'ibc/D27DDDF34BB47E5D5A570742CC667DE53277867116CCCA341F27785E899A70F3',
    coinDenom: 'MKR',
    paths: [{ portId: 'transfer', channelId: 'channel-208' }],
    originChainId: 'axelar-dojo-1',
    originCurrency: {
      coinDenom: 'MKR',
      coinMinimalDenom: 'mkr-wei',
      coinDecimals: 18,
      coinGeckoId: 'maker',
      coinImageUrl: '/tokens/mkr.svg',
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'pool:odin',
    coinImageUrl: '/tokens/odin.svg',
    coinMinimalDenom:
      'ibc/C360EF34A86D334F625E4CBB7DA3223AEA97174B61F35BB3758081A8160F7D9B',
    coinDenom: 'ODIN (channel-258)',
    paths: [{ portId: 'transfer', channelId: 'channel-258' }],
    originChainId: 'odin-mainnet-freya',
    originCurrency: {
      coinDenom: 'ODIN',
      coinMinimalDenom: 'loki',
      coinDecimals: 6,
      coinGeckoId: 'pool:odin',
      coinImageUrl: '/tokens/odin.svg',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'kujira',
    coinImageUrl: '/tokens/kuji.png',
    coinMinimalDenom:
      'ibc/BB6BCDB515050BAE97516111873CCD7BCF1FD0CCB723CC12F3C4F704D6C646CE',
    coinDenom: 'KUJI',
    paths: [{ portId: 'transfer', channelId: 'channel-259' }],
    originChainId: 'kaiyo-1',
    originCurrency: {
      coinDenom: 'KUJI',
      coinMinimalDenom: 'ukuji',
      coinDecimals: 6,
      coinGeckoId: 'kujira',
      coinImageUrl: '/tokens/kuji.png',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'pool:utgd',
    coinImageUrl: '/tokens/tgrade.svg',
    coinMinimalDenom:
      'ibc/1E09CB0F506ACF12FDE4683FB6B34DA62FB4BE122641E0D93AAF98A87675676C',
    coinDenom: 'TGD',
    paths: [{ portId: 'transfer', channelId: 'channel-263' }],
    originChainId: 'tgrade-mainnet-1',
    originCurrency: {
      coinDenom: 'TGD',
      coinMinimalDenom: 'utgd',
      coinDecimals: 6,
      coinGeckoId: 'pool:utgd',
      coinImageUrl: '/tokens/tgrade.svg',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'lvn',
    coinImageUrl: '/tokens/lvn.png',
    coinMinimalDenom:
      'ibc/AD185F62399F770CCCE8A36A180A77879FF6C26A0398BD3D2A74E087B0BFA121',
    coinDenom: 'LVN (channel-261)',
    paths: [{ portId: 'transfer', channelId: 'channel-261' }],
    originChainId: 'kichain-2',
    originCurrency: {
      type: 'cw20',
      contractAddress:
        'ki1dt3lk455ed360pna38fkhqn0p8y44qndsr77qu73ghyaz2zv4whq83mwdy',
      coinDenom: 'LVN',
      coinMinimalDenom:
        'cw20:ki1dt3lk455ed360pna38fkhqn0p8y44qndsr77qu73ghyaz2zv4whq83mwdy:LVN',
      coinDecimals: 6,
      coinGeckoId: 'lvn',
      coinImageUrl: '/tokens/lvn.png',
    },
  },
  {
    coinDecimals: 10,
    coinGeckoId: 'polkadot',
    coinImageUrl: '/tokens/dot.svg',
    coinMinimalDenom:
      'ibc/3FF92D26B407FD61AE95D975712A7C319CDE28DE4D80BDC9978D935932B991D7',
    coinDenom: 'DOT',
    paths: [{ portId: 'transfer', channelId: 'channel-208' }],
    originChainId: 'axelar-dojo-1',
    originCurrency: {
      coinDenom: 'DOT',
      coinMinimalDenom: 'dot-planck',
      coinDecimals: 10,
      coinGeckoId: 'polkadot',
      coinImageUrl: '/tokens/dot.svg',
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'pool:glto',
    coinImageUrl: '/tokens/glto.svg',
    coinMinimalDenom:
      'ibc/52C57FCA7D6854AA178E7A183DDBE4EF322B904B1D719FC485F6FFBC1F72A19E',
    coinDenom: 'GLTO (channel-169)',
    paths: [{ portId: 'transfer', channelId: 'channel-169' }],
    originChainId: 'juno-1',
    originCurrency: {
      type: 'cw20',
      contractAddress:
        'juno1j0a9ymgngasfn3l5me8qpd53l5zlm9wurfdk7r65s5mg6tkxal3qpgf5se',
      coinDenom: 'GLTO',
      coinMinimalDenom:
        'cw20:juno1j0a9ymgngasfn3l5me8qpd53l5zlm9wurfdk7r65s5mg6tkxal3qpgf5se:GLTO',
      coinDecimals: 6,
      coinGeckoId: 'pool:glto',
      coinImageUrl: '/tokens/glto.svg',
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'pool:ucre',
    coinImageUrl: '/tokens/cre.svg',
    coinMinimalDenom:
      'ibc/5A7C219BA5F7582B99629BA3B2A01A61BFDA0F6FD1FE95B5366F7334C4BC0580',
    coinDenom: 'CRE (channel-297)',
    paths: [{ portId: 'transfer', channelId: 'channel-297' }],
    originChainId: 'crescent-1',
    originCurrency: {
      coinDenom: 'CRE',
      coinMinimalDenom: 'ucre',
      coinDecimals: 6,
      coinGeckoId: 'pool:ucre',
      coinImageUrl: '/tokens/cre.svg',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'pool:geo',
    coinImageUrl: '/tokens/geo.svg',
    coinMinimalDenom:
      'ibc/9B6FBABA36BB4A3BF127AE5E96B572A5197FD9F3111D895D8919B07BC290764A',
    coinDenom: 'GEO (channel-258)',
    paths: [{ portId: 'transfer', channelId: 'channel-258' }],
    originChainId: 'odin-mainnet-freya',
    originCurrency: {
      coinDenom: 'GEO',
      coinMinimalDenom: 'mGeo',
      coinDecimals: 6,
      coinGeckoId: 'pool:geo',
      coinImageUrl: '/tokens/geo.svg',
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'pool:gkey',
    coinImageUrl: '/tokens/gkey.svg',
    coinMinimalDenom:
      'ibc/7C781B4C2082CD62129A972D47486D78EC17155C299270E3C89348EA026BEAF8',
    coinDenom: 'GKEY (channel-169)',
    paths: [{ portId: 'transfer', channelId: 'channel-169' }],
    originChainId: 'juno-1',
    originCurrency: {
      type: 'cw20',
      contractAddress:
        'juno1gz8cf86zr4vw9cjcyyv432vgdaecvr9n254d3uwwkx9rermekddsxzageh',
      coinDenom: 'GKEY',
      coinMinimalDenom:
        'cw20:juno1gz8cf86zr4vw9cjcyyv432vgdaecvr9n254d3uwwkx9rermekddsxzageh:GKEY',
      coinDecimals: 6,
      coinGeckoId: 'pool:gkey',
      coinImageUrl: '/tokens/gkey.svg',
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'usdx',
    coinImageUrl: '/tokens/usdx.png',
    coinMinimalDenom:
      'ibc/C78F65E1648A3DFE0BAEB6C4CDA69CC2A75437F1793C0E6386DFDA26393790AE',
    coinDenom: 'USDX (channel-143)',
    paths: [{ portId: 'transfer', channelId: 'channel-143' }],
    originChainId: 'kava_2222-10',
    originCurrency: {
      coinDenom: 'USDX',
      coinMinimalDenom: 'usdx',
      coinDecimals: 6,
      coinGeckoId: 'usdx',
      coinImageUrl: '/tokens/usdx.png',
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'pool:sejuno',
    coinImageUrl: '/tokens/sejuno.png',
    coinMinimalDenom:
      'ibc/C6B6BFCB6EE49A7CAB1A7E7B021DE35B99D525AC660844952F0F6C78DCB2A57B',
    coinDenom: 'seJUNO (channel-169)',
    paths: [{ portId: 'transfer', channelId: 'channel-169' }],
    originChainId: 'juno-1',
    originCurrency: {
      type: 'cw20',
      contractAddress:
        'juno1dd0k0um5rqncfueza62w9sentdfh3ec4nw4aq4lk5hkjl63vljqscth9gv',
      coinDenom: 'seJUNO',
      coinMinimalDenom:
        'cw20:juno1dd0k0um5rqncfueza62w9sentdfh3ec4nw4aq4lk5hkjl63vljqscth9gv:seJUNO',
      coinDecimals: 6,
      coinGeckoId: 'pool:sejuno',
      coinImageUrl: '/tokens/sejuno.png',
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'agoric',
    coinImageUrl: '/tokens/bld.png',
    coinMinimalDenom:
      'ibc/2DA9C149E9AD2BD27FEFA635458FB37093C256C1A940392634A16BEA45262604',
    coinDenom: 'BLD',
    paths: [{ portId: 'transfer', channelId: 'channel-320' }],
    originChainId: 'agoric-3',
    originCurrency: {
      coinDenom: 'BLD',
      coinMinimalDenom: 'ubld',
      coinDecimals: 6,
      coinGeckoId: 'agoric',
      coinImageUrl: '/tokens/bld.png',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 18,
    coinGeckoId: 'cudos',
    coinImageUrl: '/tokens/cudos.svg',
    coinMinimalDenom:
      'ibc/E09ED39F390EC51FA9F3F69BEA08B5BBE6A48B3057B2B1C3467FAAE9E58B021B',
    coinDenom: 'CUDOS (channel-298)',
    paths: [{ portId: 'transfer', channelId: 'channel-298' }],
    originChainId: 'cudos-1',
    originCurrency: {
      coinDenom: 'CUDOS',
      coinMinimalDenom: 'acudos',
      coinDecimals: 18,
      coinGeckoId: 'cudos',
      coinImageUrl: '/tokens/cudos.svg',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'oraichain-token',
    coinImageUrl: '/tokens/orai.svg',
    coinMinimalDenom:
      'ibc/161D7D62BAB3B9C39003334F1671208F43C06B643CC9EDBBE82B64793C857F1D',
    coinDenom: 'ORAI (channel-216)',
    paths: [{ portId: 'transfer', channelId: 'channel-216' }],
    originChainId: 'Oraichain',
    originCurrency: {
      coinDenom: 'ORAI',
      coinMinimalDenom: 'orai',
      coinDecimals: 6,
      coinGeckoId: 'oraichain-token',
      coinImageUrl: '/tokens/orai.svg',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'pool:stuatom',
    coinImageUrl: '/tokens/statom.svg',
    coinMinimalDenom:
      'ibc/C140AFD542AE77BD7DCC83F13FDD8C5E5BB8C4929785E6EC2F4C636F98F17901',
    coinDenom: 'stATOM',
    paths: [{ portId: 'transfer', channelId: 'channel-326' }],
    originChainId: 'stride-1',
    originCurrency: {
      coinDenom: 'stATOM',
      coinMinimalDenom: 'stuatom',
      coinDecimals: 6,
      coinGeckoId: 'pool:stuatom',
      coinImageUrl: '/tokens/statom.svg',
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'pool:o9w',
    coinImageUrl: '/tokens/o9w.svg',
    coinMinimalDenom:
      'ibc/0CD46223FEABD2AEAAAF1F057D01E63BCA79B7D4BD6B68F1EB973A987344695D',
    coinDenom: 'O9W (channel-258)',
    paths: [{ portId: 'transfer', channelId: 'channel-258' }],
    originChainId: 'odin-mainnet-freya',
    originCurrency: {
      coinDenom: 'O9W',
      coinMinimalDenom: 'mO9W',
      coinDecimals: 6,
      coinGeckoId: 'pool:o9w',
      coinImageUrl: '/tokens/o9w.svg',
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'pool:ustrd',
    coinImageUrl: '/tokens/strd.svg',
    coinMinimalDenom:
      'ibc/A8CA5EE328FA10C9519DF6057DA1F69682D28F7D0F5CCC7ECB72E3DCA2D157A4',
    coinDenom: 'STRD',
    paths: [{ portId: 'transfer', channelId: 'channel-326' }],
    originChainId: 'stride-1',
    originCurrency: {
      coinDenom: 'STRD',
      coinMinimalDenom: 'ustrd',
      coinDecimals: 6,
      coinGeckoId: 'pool:ustrd',
      coinImageUrl: '/tokens/strd.svg',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'pool:seasy',
    coinImageUrl: '/tokens/seasy.svg',
    coinMinimalDenom:
      'ibc/18A676A074F73B9B42DA4F9DFC8E5AEF334C9A6636DDEC8D34682F52F1DECDF6',
    coinDenom: 'SEASY (channel-169)',
    paths: [{ portId: 'transfer', channelId: 'channel-169' }],
    originChainId: 'juno-1',
    originCurrency: {
      type: 'cw20',
      contractAddress:
        'juno19rqljkh95gh40s7qdx40ksx3zq5tm4qsmsrdz9smw668x9zdr3lqtg33mf',
      coinDenom: 'SEASY',
      coinMinimalDenom:
        'cw20:juno19rqljkh95gh40s7qdx40ksx3zq5tm4qsmsrdz9smw668x9zdr3lqtg33mf:SEASY',
      coinDecimals: 6,
      coinGeckoId: 'pool:seasy',
      coinImageUrl: '/tokens/seasy.svg',
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'pool:stustars',
    coinImageUrl: '/tokens/ststars.svg',
    coinMinimalDenom:
      'ibc/5DD1F95ED336014D00CE2520977EC71566D282F9749170ADC83A392E0EA7426A',
    coinDenom: 'stSTARS (channel-326)',
    paths: [{ portId: 'transfer', channelId: 'channel-326' }],
    originChainId: 'stride-1',
    originCurrency: {
      coinDenom: 'stSTARS',
      coinMinimalDenom: 'stustars',
      coinDecimals: 6,
      coinGeckoId: 'pool:stustars',
      coinImageUrl: '/tokens/ststars.svg',
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'pool:uaxl',
    coinImageUrl: '/tokens/axl.svg',
    coinMinimalDenom:
      'ibc/903A61A498756EA560B85A85132D3AEE21B5DEDD41213725D22ABF276EA6945E',
    coinDenom: 'AXL',
    paths: [{ portId: 'transfer', channelId: 'channel-208' }],
    originChainId: 'axelar-dojo-1',
    originCurrency: {
      coinDenom: 'AXL',
      coinMinimalDenom: 'uaxl',
      coinDecimals: 6,
      coinGeckoId: 'pool:uaxl',
      coinImageUrl: '/tokens/axl.svg',
    },
  },
  {
    coinDecimals: 18,
    coinGeckoId: 'pool:arebus',
    coinImageUrl: '/tokens/rebus.png',
    coinMinimalDenom:
      'ibc/A1AC7F9EE2F643A68E3A35BCEB22040120BEA4059773BB56985C76BDFEBC71D9',
    coinDenom: 'REBUS (channel-355)',
    paths: [{ portId: 'transfer', channelId: 'channel-355' }],
    originChainId: 'reb_1111-1',
    originCurrency: {
      coinDenom: 'REBUS',
      coinMinimalDenom: 'arebus',
      coinDecimals: 18,
      coinGeckoId: 'pool:arebus',
      coinImageUrl: '/tokens/rebus.png',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'pool:utori',
    coinImageUrl: '/tokens/utori.png',
    coinMinimalDenom:
      'ibc/EB7FB9C8B425F289B63703413327C2051030E848CE4EAAEA2E51199D6D39D3EC',
    coinDenom: 'TORI (channel-362)',
    paths: [{ portId: 'transfer', channelId: 'channel-362' }],
    originChainId: 'teritori-1',
    originCurrency: {
      coinDenom: 'TORI',
      coinMinimalDenom: 'utori',
      coinDecimals: 6,
      coinGeckoId: 'pool:utori',
      coinImageUrl: '/tokens/utori.png',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'pool:stujuno',
    coinImageUrl: '/tokens/stjuno.svg',
    coinMinimalDenom:
      'ibc/84502A75BCA4A5F68D464C00B3F610CE2585847D59B52E5FFB7C3C9D2DDCD3FE',
    coinDenom: 'stJUNO (channel-326)',
    paths: [{ portId: 'transfer', channelId: 'channel-326' }],
    originChainId: 'stride-1',
    originCurrency: {
      coinDenom: 'stJUNO',
      coinMinimalDenom: 'stujuno',
      coinDecimals: 6,
      coinGeckoId: 'pool:stujuno',
      coinImageUrl: '/tokens/stjuno.svg',
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'tether',
    coinImageUrl: '/tokens/gusdt.png',
    coinMinimalDenom:
      'ibc/71B441E27F1BBB44DD0891BCD370C2794D404D60A4FFE5AECCD9B1E28BC89805',
    coinDenom: 'USDT.grv (channel-144)',
    paths: [{ portId: 'transfer', channelId: 'channel-144' }],
    originChainId: 'gravity-bridge-3',
    originCurrency: {
      coinDenom: 'USDT.grv',
      coinMinimalDenom: 'gravity0xdAC17F958D2ee523a2206206994597C13D831ec7',
      coinDecimals: 6,
      coinGeckoId: 'tether',
      coinImageUrl: '/tokens/gusdt.png',
      pegMechanism: 'collateralized',
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'usk',
    coinImageUrl: '/tokens/usk.png',
    coinMinimalDenom:
      'ibc/44492EAB24B72E3FB59B9FA619A22337FB74F95D8808FE6BC78CC0E6C18DC2EC',
    coinDenom: 'USK (channel-259)',
    paths: [{ portId: 'transfer', channelId: 'channel-259' }],
    originChainId: 'kaiyo-1',
    originCurrency: {
      coinDenom: 'USK',
      coinMinimalDenom:
        'factory:kujira1qk00h5atutpsv900x202pxx42npjr9thg58dnqpa72f2p7m2luase444a7:uusk',
      coinDecimals: 6,
      coinGeckoId: 'usk',
      coinImageUrl: '/tokens/usk.png',
    },
  },
  {
    coinDecimals: 18,
    coinGeckoId: 'pool:lambda',
    coinImageUrl: '/tokens/lambda.png',
    coinMinimalDenom:
      'ibc/80825E8F04B12D914ABEADB1F4D39C04755B12C8402F6876EE3168450C0A90BB',
    coinDenom: 'LAMB (channel-378)',
    paths: [{ portId: 'transfer', channelId: 'channel-378' }],
    originChainId: 'lambda_92000-1',
    originCurrency: {
      coinDenom: 'LAMB',
      coinMinimalDenom: 'ulamb',
      coinDecimals: 18,
      coinGeckoId: 'pool:lambda',
      coinImageUrl: '/tokens/lambda.png',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 18,
    coinGeckoId: 'wrapped-moonbeam',
    coinImageUrl: '/tokens/glmr.svg',
    coinMinimalDenom:
      'ibc/1E26DB0E5122AED464D98462BD384FCCB595732A66B3970AE6CE0B58BAE0FC49',
    coinDenom: 'WGLMR (channel-208)',
    paths: [{ portId: 'transfer', channelId: 'channel-208' }],
    originChainId: 'axelar-dojo-1',
    originCurrency: {
      coinDenom: 'WGLMR',
      coinMinimalDenom: 'wglmr-wei',
      coinDecimals: 18,
      coinGeckoId: 'wrapped-moonbeam',
      coinImageUrl: '/tokens/glmr.svg',
    },
  },
  {
    coinDecimals: 9,
    coinGeckoId: 'unification',
    coinImageUrl: '/tokens/fund.png',
    coinMinimalDenom:
      'ibc/608EF5C0CE64FEA097500DB39657BDD36CA708CC5DCC2E250A024B6981DD36BC',
    coinDenom: 'FUND (channel-382)',
    paths: [{ portId: 'transfer', channelId: 'channel-382' }],
    originChainId: 'FUND-MainNet-2',
    originCurrency: {
      coinDenom: 'FUND',
      coinMinimalDenom: 'nund',
      coinDecimals: 9,
      coinGeckoId: 'unification',
      coinImageUrl: '/tokens/fund.png',
      isStakeCurrency: true,
      isFeeCurrency: true,
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'pool:stuosmo',
    coinImageUrl: '/tokens/stosmo.svg',
    coinMinimalDenom:
      'ibc/D176154B0C63D1F9C6DCFB4F70349EBF2E2B5A87A05902F57A6AE92B863E9AEC',
    coinDenom: 'stOSMO (channel-326)',
    paths: [{ portId: 'transfer', channelId: 'channel-326' }],
    originChainId: 'stride-1',
    originCurrency: {
      coinDenom: 'stOSMO',
      coinMinimalDenom: 'stuosmo',
      coinDecimals: 6,
      coinGeckoId: 'pool:stuosmo',
      coinImageUrl: '/tokens/stosmo.svg',
    },
  },
  {
    coinDecimals: 6,
    coinGeckoId: 'pool:uist',
    coinImageUrl: '/tokens/ist.png',
    coinMinimalDenom:
      'ibc/92BE0717F4678905E53F4E45B2DED18BC0CB97BF1F8B6A25AFEDF3D5A879B4D5',
    coinDenom: 'IST (channel-320)',
    paths: [{ portId: 'transfer', channelId: 'channel-320' }],
    originChainId: 'agoric-3',
    originCurrency: {
      coinDenom: 'IST',
      coinMinimalDenom: 'uist',
      coinDecimals: 6,
      coinGeckoId: 'pool:uist',
      coinImageUrl: '/tokens/ist.png',
    },
  },
  {
    coinDecimals: 18,
    coinGeckoId: 'wbnb',
    coinImageUrl: '/tokens/wbnb.svg',
    coinMinimalDenom:
      'ibc/F4A070A6D78496D53127EA85C094A9EC87DFC1F36071B8CCDDBD020F933D213D',
    coinDenom: 'WBNB (channel-208)',
    paths: [{ portId: 'transfer', channelId: 'channel-208' }],
    originChainId: 'axelar-dojo-1',
    originCurrency: {
      coinDenom: 'WBNB',
      coinMinimalDenom: 'wbnb-wei',
      coinDecimals: 18,
      coinGeckoId: 'wbnb',
      coinImageUrl: '/tokens/wbnb.svg',
    },
  },
];
